name: CI Pipeline

on:
  push:
    branches:
      - addEslint
    
  workflow_dispatch:

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3


    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - uses: actions/setup-node@v2
        with:
        node-version: '14'
        
    - name: Run ESLint
      run: npm run lint
