name: CI Pipeline

on:
  push:
    branches:
      - addEslint
  workflow_dispatch:

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Setup ESLint
      run: npm install eslint eslint-config-airbnb-base --save-dev  # Instala ESLint e uma configuração base (exemplo)

    - name: Run ESLint
      run: npm run lint